### ISSUE TITLE
How to run all cards?

### ISSUE THREAD

**Issue by Quake4** [KL0nLutiy/sgminer-kl#13]
![image](https://user-images.githubusercontent.com/29517243/44014952-2fa081d0-9ed7-11e8-9907-fea810b2d588.png)

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/44015014-9653f92a-9ed7-11e8-80f8-58d6fb8cea03.png)
Run command like this.

**Comment by KL0nLutiy** [comment]
Did you try without --gpu-platform 1?

**Comment by Quake4** [comment]
yes. but isnt working

**Comment by Quake4** [comment]
and tre `-d` - same

**Comment by KL0nLutiy** [comment]
It's very strange, could you please test this version https://drive.google.com/file/d/1EsI6k-5speFD1q78pLqaKxAzoefHxh81/view?usp=sharing
Could you provide info which version of driver did you use, did the cards overclocked or undervolted and the models of the cards?

**Comment by KL0nLutiy** [comment]
@Quake4, please try last version: https://github.com/KL0nLutiy/sgminer-kl/releases/tag/kl-1.0.6
