### ISSUE TITLE
bug with block found

### ISSUE THREAD

**Issue by Quake4** [KL0nLutiy/sgminer-kl#14]
wrong found block output
no new `hash order` after found block output
![image](https://user-images.githubusercontent.com/29517243/44384894-64021b00-a526-11e8-8ab0-bb70d246452c.png)
and in block expolorer isnt my wallet

**Comment by KL0nLutiy** [comment]
@Quake4, please try last version: https://github.com/KL0nLutiy/sgminer-kl/releases/tag/kl-1.0.6

**Comment by KL0nLutiy** [comment]
@Quake4, reopen if bug still exist
