### ISSUE TITLE
Issue: AMD Vega 56 Hard Hang

### ISSUE THREAD

**Issue by Byrd1083** [KL0nLutiy/sgminer-kl#16]
Running Windows 10 pro 1803
Gigabyte Vega 56 oc gaming edition.

Hard hang at start won't show any hash rate but still responds. Try to close the program or hit the x to close window. Window will not close even trying to kill in task manager, it still will not close. Have to restart system to close. I have cast-xmr cryptonightv7 running 1900 h/s no problem so I know it is not hardware.

**Comment by KL0nLutiy** [comment]
@Byrd1083, please try last version: https://github.com/KL0nLutiy/sgminer-kl/releases/tag/kl-1.0.6

**Comment by KL0nLutiy** [comment]
@Byrd1083, reopen if bug still exist
