### ISSUE TITLE
failure to compile (unix)

### ISSUE THREAD

**Issue by MaynardMiner** [KL0nLutiy/sgminer-kl#18]
make[2]: Entering directory '/root/sgminer-kl/sph'
  CC       bmw.o
  CC       echo.o
  CC       jh.o
  CC       luffa.o
  CC       simd.o
  CC       blake.o
  CC       cubehash.o
  CC       groestl.o
  CC       keccak.o
  CC       shavite.o
  CC       skein.o
  CC       sha2.o
  CC       sha2big.o
  CC       fugue.o
  CC       gost.o
  CC       hamsi.o
  CC       haval.o
  CC       panama.o
  CC       shabal.o
  CC       whirlpool.o
  CC       sha256_Y.o
In file included from ../miner.h:17:0,
                 from sha256_Y.c:35:
../algorithm.h:7:19: fatal error: CL/cl.h: No such file or directory
compilation terminated.
In file included from ../miner.h:17:0,
                 from sha256_Y.c:35:
../algorithm.h:7:19: fatal error: CL/cl.h: No such file or directory
compilation terminated.
Makefile:538: recipe for target 'sha256_Y.o' failed
make[2]: *** [sha256_Y.o] Error 1
make[2]: Leaving directory '/root/sgminer-kl/sph'
Makefile:1923: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/sgminer-kl'
Makefile:678: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MaynardMiner** [comment]
../algorithm.h:7:19: fatal error: CL/cl.h: No such file or directory

I'm pretty sure that should be CL/ocl.h

I can' figure out where to edit to change that.

**Comment by MaynardMiner** [comment]
It's in aglorithm.h

I was wrong. I tried it.

**Comment by MaynardMiner** [comment]
root@AMD:~/sgminer-kl# find / -iname cl.h 2>/dev/null
/opt/AMDAPPSDK-3.0/include/CL/cl.h

It looks like I have that file

**Comment by MaynardMiner** [comment]
FILE _iob[] = { *stdin, *stdout, *stderr };
extern "C" FILE * __cdecl __iob_func(void) { return _iob; }

-"*stdin,*stdout,*stderr" expression must have a constant value
-"C" expected and identifier

Cannot be compiled as is because of this. Just thought you should know.

**Comment by MaynardMiner** [comment]
It works fine when I remove those two lines from code, and well- So good job.

Quick question though, if you can help a newb:

Is there a way to compile a binary with flags that will generate an all-purpose binary for Unix? When I compile it, it compiles and works fine in my system, but when I when another user tries it fails.

I have been working on adding AMD to my profit-switching miner for HiveOS, and I can't seem to compile a binary that works for other users. It seems to only work with my system. I've compiled plenty of ccminers- I am new to AMD.

**Comment by KL0nLutiy** [comment]
I not shure why it is may not work, but if it not working, the other iser must to recompile it.

**Comment by MaynardMiner** [comment]
So should I design it then to compile in their rig, then?

I can do that.

It's just weird that avermore released binary is the only sgminer that seems to work on multiple user systems. All other ones I attempt to compile and add file.

**Comment by geebeezzz1** [comment]
did you fix it?

i try to install it on smos with no success

**Comment by MaynardMiner** [comment]
remove these lines in sgminer.c

FILE _iob[] = { *stdin, *stdout, *stderr };
extern "C" FILE * __cdecl __iob_func(void) { return _iob; }

It will compile. I'm assuming he has them for visual basic...I'm guessing.

My repo has a version with the lines removed.
