### ISSUE TITLE
HiveOS bug

### ISSUE THREAD

**Issue by MoNTE48** [KL0nLutiy/sgminer-kl#2]
Hi. On HiveOS awermore mner work perfectly, but your miner get error:
/hive/sgminer/sgminer.sh: line 31: 20844 **Illegal instruction**     ./$fork/sgminer -c sgminer.conf $SGMINER_GM_CLI_ARGS

**Comment by KL0nLutiy** [comment]
@MoNTE48, please, try the lask linux build: https://github.com/KL0nLutiy/sgminer-kl/releases/tag/kl-1.0.5

**Comment by MoNTE48** [comment]
@KL0nLutiy, yes, it work for me. Please, recompile miner without flag --disable-adl and with curses lib!

**Comment by KL0nLutiy** [comment]
@MoNTE48, done. I reupload linux version with new build: https://github.com/KL0nLutiy/sgminer-kl/releases/tag/kl-1.0.5

**Comment by MoNTE48** [comment]
Now this works fine, the only problem I see with the HiveOS API.
![api](https://user-images.githubusercontent.com/6764600/40891568-0d7d45ce-6788-11e8-9588-fa0c90c663fb.PNG)
On avermore and other sgminer fork API work!

**Comment by MoNTE48** [comment]
You can try this: https://github.com/KL0nLutiy/sgminer-kl/blob/master/ADL_SDK/readme.txt#L1
You can find this files there: https://github.com/GPUOpen-Tools/common-lib-amd-ADL/tree/master/include

**Comment by KL0nLutiy** [comment]
@MoNTE48, sorry, forgot to add adl. Reupload with included adl: https://github.com/KL0nLutiy/sgminer-kl/releases/tag/kl-1.0.5

**Comment by MoNTE48** [comment]
Yes, now your miner work fine for me! I'll give him a day's work and I'll tell you the result.

**Comment by KL0nLutiy** [comment]
@MoNTE48 do you have any results?
