### ISSUE TITLE
linker errors LNK2001 - dependencies available

### ISSUE THREAD

**Issue by cryptorex** [KL0nLutiy/sgminer-kl#4]
Getting linker errors - I'm sure I've gone through the winbuild dependencies and builds.

Getting these linker errors but I've followed README viciously.

Using VS2013.  Thanks 

![image](https://user-images.githubusercontent.com/30375892/41185333-ce251050-6b4c-11e8-9a5f-25d9705660df.png)

**Comment by KL0nLutiy** [comment]
@cryptorex so you did something wrong. Did you try to compile x32 or x64 version?
