### ISSUE TITLE
64 Bit Pointer Support

### ISSUE THREAD

**Issue by Exodus4400** [KL0nLutiy/sgminer-kl#5]
Miner doesn't work with GPU_FORCE_64BIT_PTR 1. I use Multipoolminer and this would be a great miner to add into the rotation because it covers algorithms for AMD cards that there are not currently miners for. Could you add support for 64 Bit pointers?

**Comment by Exodus4400** [comment]
Aergo, phi, tribus, x16r, x16s, x17, and xevan. For example, if I run the below batch file, it will quit. Variable changed is in bold.

**set GPU_FORCE_64BIT_PTR=1**
set GPU_USE_SYNC_OBJECTS=1
set GPU_MAX_ALLOC_PERCENT=100
set GPU_SINGLE_ALLOC_PERCENT=100
set GPU_MAX_HEAP_SIZE=100

sgminer.exe -k x16s -o stratum+tcp://x16s.mine.zpool.ca:3663 -u 3Bh7gjE4aNZzkFD6eu3jGKGHw3aw5vRfL6 -p donate -X 256 --gpu-platform=1 -g 2 --log-file log.txt
pause

**Comment by KL0nLutiy** [comment]
To use GPU_FORCE_64BIT_PTR, you need sgminer x64, I will compile and attech it. But I am not sure, if it give any perfomance increase.

**Comment by Exodus4400** [comment]
It's more for convenience. The multipoolminer sets environment variables on startup because some of the other miners do benefit from the having the 64 bit pointer. You can check out the project here: https://github.com/MultiPoolMiner/MultiPoolMiner

**Comment by KL0nLutiy** [comment]
Please try the 64 bit version https://github.com/KL0nLutiy/sgminer-kl/releases/tag/kl-1.0.5fix and share your result.

**Comment by Exodus4400** [comment]
That works great. Thanks for your help.
